In [1]:
import numpy as np

x = np.array([1, 2, 3])
x.__class__
x.shape

numpy.ndarray

In [2]:
x.shape

(3,)

In [3]:
x.ndim

1

In [5]:
W = np.array([[1, 2, 3], [4, 5, 6]])
W.shape

(2, 3)

In [6]:
W.ndim

2

----------------------------------------------------------------------------------------------------------------

In [7]:
A = np.array([[1, 2], [3, 4]])
A * 10

array([[10, 20],
       [30, 40]])

In [11]:
import numpy as np
W1 = np.random.randn(2, 4)
b1 = np.random.randn(4)
x = np.random.randn(10, 2)
h = np.matmul(x, W1) + b1
print(x)
print(h)

[[ 0.39549722 -0.2728192 ]
 [ 0.3941871  -0.44218284]
 [ 0.11335373  0.34202577]
 [-1.54858608 -1.15047352]
 [-1.48381074  0.07557748]
 [ 1.12138734 -1.39272183]
 [ 0.31444267  0.09898867]
 [-1.08368275 -0.21879162]
 [-3.44558047  0.09746159]
 [ 0.92313149 -1.41310282]]
[[ 0.083218    0.07019144 -1.78772346  1.18321802]
 [ 0.24257903 -0.27019349 -1.88488655  1.26553012]
 [-0.70480848  0.91746045 -1.15653371  0.96988777]
 [-0.50557484 -4.31664536 -0.41095012  2.18703335]
 [-1.61884168 -1.77768367  0.23876545  1.57468718]
 [ 1.67335023 -1.18604983 -3.14314135  1.50862013]
 [-0.32791713  0.70381093 -1.49295848  1.02752577]
 [-1.04802165 -1.82447937 -0.32067494  1.59784566]
 [-3.07204191 -4.3900065   2.15551917  2.14866315]
 [ 1.54787615 -1.49522008 -2.96256569  1.57755407]]


## sigmoid 함수  
<p align="center"><img src="sigmoid_image.jpeg" width=350 />  

$$ \sigma (x) = \frac{1}{1+exp(-x)}$$  


In [12]:
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

In [14]:
a = sigmoid(h)
print(a)    

[[0.5207925  0.51754066 0.14335206 0.76552592]
 [0.56034911 0.43285959 0.1318286  0.77997662]
 [0.33074699 0.71452437 0.2392977  0.72509713]
 [0.37623146 0.01316884 0.39868432 0.89907904]
 [0.16536468 0.14458939 0.55940939 0.82845078]
 [0.84202198 0.23396616 0.04136238 0.81885662]
 [0.4187475  0.66903216 0.18347809 0.73643593]
 [0.25960518 0.13889725 0.42051127 0.83171707]
 [0.04427534 0.01224876 0.8961834  0.89554379]
 [0.82460677 0.18313951 0.04914597 0.82885784]]


In [21]:
import numpy as np

def Sigmoid(x):
    return 1 / (1 + np.exp(-x))

x = np.random.randn(10, 2)
W1 = np.random.randn(2, 4)
b1 = np.random.randn(4)
W2 = np.random.randn(4, 3)
b2 = np.random.randn(3)

h = np.matmul(x, W1) + b1
a = Sigmoid(h)
s = np.matmul(a, W2) + b2

print(s)

[[ 0.38884657  0.64404707 -2.07157866]
 [ 0.17149014  0.51138197 -2.00026048]
 [ 0.44811462  0.7052101  -1.58867883]
 [ 0.1359015   0.49894179 -2.00353942]
 [ 0.25019305  0.56735892 -1.93253183]
 [ 0.45368934  0.68378155 -1.9164727 ]
 [ 0.58189032  0.6959818  -1.22445713]
 [ 0.58907025  0.71611732 -1.07091867]
 [ 0.57833167  0.68801722 -1.40340735]
 [ 0.17434293  0.51369546 -2.03748845]]


## 1.2.2 계층으로 클래스화 및 순전파 구현

---

#### 계층의 '구현 규칙'
- 모든 계층은 `forward()`와 `backward()` 메서드를 가진다.
- 모든 계층은 인스턴스 변수인 `params`와 `grads`를 가진다.

`forward()` : 순전파 수행  
`backward()` : 역전파 수행  
`params` : 가중치와 편향 같은 매개변수를 담는 리스트  
`grads` : `params`에 저장된 각 매개변수에 대응하여, 해당 매개변수의 기울기를 저장하는 리스트

---

**Sigmoid layer 구현**

In [27]:
# sigmoid layer

class Sigmoid:
    def __init__(self):
        self.params = [] # 학습하는 매개변수가 따로 없기 때문에 빈 리스트로 초기화
        
    def forward(self, x):
        return 1 / (1 + np.exp(-x))
    

**Affine layer 구현**

In [28]:
# Affine layer

class Affine:
    def __init__(self, W, b):
        self.params = [W, b]
        
    def forward(self, x):
        W, b = self.params
        out = np.matmul(x, W) + b
        return out


#### TwoLayerNet 구현

<p align="center"><img src="TwoLayerNet.jpeg" width=500 />

In [29]:
class TwoLayerNet:
    def __init__(self, input_size, hidden_size, output_size):
        I, H, O = input_size, hidden_size, output_size
        
        # 가중치와 편향 초기화
        W1 = np.random.randn(I, H)
        b1 = np.random.randn(H)
        W2 = np.random.randn(H, O)
        b2 = np.random.randn(O)
        
        # 계층 생성
        self.layers = [
            Affine(W1, b1),
            Sigmoid(),
            Affine(W2, b2)
        ]
        
        # 모든 가중치를 리스트에 모은다.
        self.params = []
        for layer in self.layers:
            self.params += layer.params
            
    def predict(self, x):
        for layer in self.layers:
            x = layer.forward(x)
            
        return x

In [32]:
x = np.random.randn(10, 2)
model = TwoLayerNet(2, 4, 3)
model.predict(x)

array([[1.34095522, 0.74129703, 0.49332718],
       [1.97880926, 0.80493484, 0.44497372],
       [1.33120103, 0.76049541, 0.52106315],
       [2.25694749, 0.58238676, 0.53752804],
       [1.77017111, 0.79963216, 0.46025231],
       [1.56086742, 0.78166663, 0.48789872],
       [1.23235684, 0.75161666, 0.51555359],
       [1.26433717, 0.75661633, 0.53026745],
       [1.25648095, 0.75523591, 0.51987568],
       [2.16437014, 0.76695699, 0.46676306]])

## 1.3 신경망의 학습

#### Repeat node

In [36]:
import numpy as np
D, N = 8, 7
x = np.random.randn(1, D)
y = np.repeat(x, N, axis=0)

In [38]:
dy = np.random.randn(N, D)
dx = np.sum(dy, axis=0, keepdims=True)
print(dx)

[[-2.81538876  4.54508744  1.09320473  0.40222119 -3.90729979 -4.49049587
   0.85953102  0.24253246]]


#### Sum node

In [39]:
import numpy as np
D, N = 8, 7
x = np.random.randn(N, D)
y = np.sum(x, axis=0, keepdims=True)

In [40]:
dy = np.random.randn(1, D)
dx = np.repeat(dy, N, axis=0)